-- V1__init_schema.sql
-- Migración inicial: Creación de tablas core del sistema de logística

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo_postal VARCHAR(255) NOT NULL,
    direccion_principal VARCHAR(255) NOT NULL,
    documento_cuit VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    nombre_razon_social VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE vehiculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    capacidad_max_peso_kg FLOAT(53),
    capacidad_max_vol_dm3 FLOAT(53),
    rango_temperatura_max FLOAT(53),
    rango_temperatura_min FLOAT(53),
    refrigerado BOOLEAN NOT NULL,
    patente VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE paquete (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(255) NOT NULL,
    tipo_paquete VARCHAR(31) NOT NULL,
    peso_kg FLOAT(53),
    volumen_dm3 FLOAT(53),
    PRIMARY KEY (id)
);

CREATE TABLE paquete_fragil (
    id BIGINT NOT NULL,
    nivel_fragilidad VARCHAR(255) NOT NULL CHECK (nivel_fragilidad IN ('BAJA','MEDIA','ALTA')),
    seguro_adicional BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE paquete_refrigerado (
    id BIGINT NOT NULL,
    horas_max_fuera_de_frio INTEGER,
    rango_max FLOAT(53) NOT NULL,
    rango_min FLOAT(53) NOT NULL,
    temperatura_objetivo FLOAT(53) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE envios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo_unico VARCHAR(255) NOT NULL UNIQUE,
    codigo_postal VARCHAR(255) NOT NULL,
    direccion_entrega VARCHAR(255) NOT NULL,
    comprobante_entrega VARCHAR(255),
    estado VARCHAR(255) NOT NULL CHECK (estado IN ('GENERADO','EN_ALMACEN','EN_RUTA','ENTREGADO','DEVUELTO','CANCELADO')),
    requiere_frio BOOLEAN,
    remitente_id BIGINT NOT NULL,
    destinatario_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE historial_estado_envio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha_hora TIMESTAMP(6),
    estado_anterior VARCHAR(255) CHECK (estado_anterior IN ('GENERADO','EN_ALMACEN','EN_RUTA','ENTREGADO','DEVUELTO','CANCELADO')),
    estado_nuevo VARCHAR(255) CHECK (estado_nuevo IN ('GENERADO','EN_ALMACEN','EN_RUTA','ENTREGADO','DEVUELTO','CANCELADO')),
    observacion VARCHAR(255),
    envio_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE ruta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    vehiculo_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE envios_paquetes (
    envio_id BIGINT NOT NULL,
    paquetes_id BIGINT NOT NULL UNIQUE
);

CREATE TABLE ruta_envios (
    ruta_id BIGINT NOT NULL,
    envios_id BIGINT NOT NULL UNIQUE
);

-- RELACIONES (Foreign Keys)
ALTER TABLE paquete_fragil ADD CONSTRAINT FK_paquete_fragil_paquete FOREIGN KEY (id) REFERENCES paquete;
ALTER TABLE paquete_refrigerado ADD CONSTRAINT FK_paquete_refri_paquete FOREIGN KEY (id) REFERENCES paquete;

ALTER TABLE envios ADD CONSTRAINT FK_envios_remitente FOREIGN KEY (remitente_id) REFERENCES clientes;
ALTER TABLE envios ADD CONSTRAINT FK_envios_destinatario FOREIGN KEY (destinatario_id) REFERENCES clientes;

ALTER TABLE historial_estado_envio ADD CONSTRAINT FK_historial_envio FOREIGN KEY (envio_id) REFERENCES envios;

ALTER TABLE ruta ADD CONSTRAINT FK_ruta_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES vehiculo;

ALTER TABLE envios_paquetes ADD CONSTRAINT FK_envios_paquetes_paquete FOREIGN KEY (paquetes_id) REFERENCES paquete;
ALTER TABLE envios_paquetes ADD CONSTRAINT FK_envios_paquetes_envio FOREIGN KEY (envio_id) REFERENCES envios;

ALTER TABLE ruta_envios ADD CONSTRAINT FK_ruta_envios_envio FOREIGN KEY (envios_id) REFERENCES envios;
ALTER TABLE ruta_envios ADD CONSTRAINT FK_ruta_envios_ruta FOREIGN KEY (ruta_id) REFERENCES ruta;
