-- V2__add_security_tables.sql
-- Migración para el sistema de seguridad y autenticación (JWT)

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL CHECK (rol IN ('ROLE_ADMIN','ROLE_EMPLEADO','ROLE_CLIENTE')),
    PRIMARY KEY (id)
);
